### ISSUE TITLE
So hard to nitpick at you Mr. Software Engineer Man

### ISSUE THREAD

**Issue by SalomonSmeke** [jthompson18/COMP330#2]
Hi. I know you did this very intensely and carefully.

So. frick you, because I have to double check everything to find somewhere to give you some constructive criticism.

I did! Actually. But it was ruff.

Your test cases cover everything. They're also super sterile. Im of the idea you should have some complex dirty test that still passes.

Example:

`#message%` is a super sterile test
`#message%@ Hi shouldnotparse #hello` is a more... rough treatment of your code

I also didn't see any tests for empty strings. But I might have missed them, python isn't my thing.

Finally, a joke:
QA Engineer walks into a bar. Orders a beer. Orders 0 beers. Orders 999999999 beers. Orders a lizard. Orders -1 beers. Orders a sfdeljknesv.

applicable. test for some lizards, homie. make your tests designed to fail.

**Comment by jthompson18** [comment]
You're right, I don't have any tests for empty strings or for complex dirty strings. I did this for two reasons.

The first pertains to the empty string testing, I used the python re library for my regex and message parsing; therefore, I didn't think it necessary to test how re.findall() performed when run against an empty string, because it is already documented that it finds no matches and returns an empty List.

The second is related to the no dirty tests, I didn't want to test multiple conditions within a single test. Instead I have tests for the private parsing methods that test parts of dirty messages to make sure each regex only matchs the portion that is should. I felt this was a good separation of concerns because if one of those test fail I know the exact regex that isn't working properly.

**Comment by SalomonSmeke** [comment]
cool! good to hear there was reasoning. I don't quite understand the explanation to dirty tests. but thats through faults of my own knowledge and understanding I'm sure.

thanks for explaining!

**Comment by jthompson18** [comment]
@SalomonSmeke does this make more sense => The dirty tests would be redundant because I am already directly dirty testing the regexs individually through the private [methods](https://github.com/jthompson18/COMP330/blob/master/tests/test_messageparser.py#L85). parse_message uses those private methods to handle tweet parsing. So if the dirty tests pass individually then their cartesian product will also pass.

**Comment by jthompson18** [comment]
@SalomonSmeke closing this. If you have any other questions please open another ticket
