### ISSUE TITLE
Testing Shortened Links?

### ISSUE THREAD

**Issue by chernandez7** [jthompson18/COMP330#3]
I'm not sure if I am interpreting the script correctly but from what I can see all the URI's being tested are checking for `http://`. If this is the case then would the tests fail for links that are automatically shortened by twitter? 
For example:
`LIVE: President Obama is speaking in Springfield, Illinois. ofa.bo/z096`

If I am incorrect in this then the issue can be closed.

**Comment by jthompson18** [comment]
@chernandez7 In the docs I specify that the links are validated and shortened in a specific format before getting to this module a link that doesn't start with http(s):// will not make it to the module therefore it isn't a valid test. Such a test would fail and that is the preferred behavior. 

I avoided writing @shouldfail tests for this project because I was concerned that they could confuse people. The out put for the running the test will show failed tests but still say it passed all.

**Comment by chernandez7** [comment]
Ah, I missed seeing that line. Thanks for the clarification.
